name: CI

on: 
  push:
   branches:
    - master
    - release/*
  schedule:
    - cron: 0 2 * * 1-5

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: fetch sources
      run: ~/.local/bin/deno fetch test.ts
    - name: run test
      run: ~/.local/bin/deno run test.ts
    - name: fetch example app
      run: ~/.local/bin/deno fetch example/server.ts
