name: TEST

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - name: fetch sources
      run: ~/.deno/bin/deno fetch test.ts
    - name: run test
      run: ~/.deno/bin/deno run test.ts
    - name: fetch example app
      run: ~/.deno/bin/deno fetch example/server.ts
